### ISSUE TITLE
Checking for liblo fails

### ISSUE THREAD

**Issue by barksten** [monome/libmonome#43]
`waf configure`
fails with Checking for liblo.

I couldn't find any information about this dependency.
I installed it with
`brew install liblo`
(I'm on a mac)
but waf still fails:

> ['/usr/bin/clang', 'test.c.1.o', '-o', 'libmonome/build/.conf_check_2b591adc3300f330d1bbd3f91f2ee0d7/testbuild/testprog', '-llo']
> err: ld: library not found for -llo
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

Is there a way to specify the path or something?

**Comment by barksten** [comment]
Related thread on lines:
[Libmonome C programming](http://llllllll.co/t/libmonome-c-programming/2774/2)

**Comment by amj** [comment]
@barksten did you get this figured?  hit the same thing last night, did the exact same thing too, `brew install liblo` and then headed over here to see if anyone knew what was up ;)

**Comment by simonvanderveldt** [comment]
@barksten @amj Is this still the case/happening for you?

**Comment by barksten** [comment]
I'm sorry, I've sold my grid almost a year ago and have not been around this ever since.

**Comment by simonvanderveldt** [comment]
> I'm sorry, I've sold my grid almost a year ago and have not been around this ever since.

@barksten No need to apologize ;) Thanks for the response!

I'll see if I can do some testing on macOS to check if this still happens.

**Comment by colinmcardell** [comment]
FYI - I just ran through the build process on macOS Sierra 10.12.6 with success, hopefully this is helpful:
![libmonome_liblo](https://user-images.githubusercontent.com/473016/33231903-fd061a16-d1ca-11e7-8ff4-f5168601882f.png)
