### ISSUE TITLE
Homepage is not reachable

### ISSUE THREAD

**Issue by ilovezfs** [monome/libmonome#47]
```
iMac-TMP:~ joe$ curl -I http://illest.net/libmonome/ -v --connect-timeout 20
*   Trying 149.210.139.23...
* Connection timed out after 20010 milliseconds
* Closing connection 0
curl: (28) Connection timed out after 20010 milliseconds
iMac-TMP:~ joe$
```

**Comment by wrl** [comment]
Yeah, I'm not doing anything with that domain right now. The homepage wasn't very good, and the documentation was out of sync with the state of the code, too. I've just removed the homepage address, and if I can track down the source HTML perhaps put it up on Github pages.
