### ISSUE TITLE
Compilation fails when building without udev

### ISSUE THREAD

**Issue by simonvanderveldt** [monome/libmonome#50]
When building without udev I get the following error
```
../src/platform/linux_sysfs.c: In function ‘monome_platform_get_dev_serial’:
../src/platform/linux_sysfs.c:71:2: error: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Werror=unused-result]
  asprintf(&buf, FTDI_PATH "/*/%s", path);
  ^
../src/platform/linux_sysfs.c: At top level:
cc1: error: unrecognized command line option ‘-Wno-initializer-overrides’ [-Werror]
cc1: all warnings being treated as errors
```

**Comment by tehn** [comment]
is udev not a requirement?

**Comment by simonvanderveldt** [comment]
> is udev not a requirement?

@tehn AFAIK not, building libmonome will fall back to using sysfs if udev is missing.
I gathered this from #1 as well as https://github.com/monome/libmonome/blob/2792f1e6bbff5c0f64b80e893a109b3e5c0c47b9/wscript#L52 and @wrl's answer on #monome on IRC.

The above error is caused by the code for the sysfs implementation, that's why it only triggers when building without udev.

**Comment by tehn** [comment]
ok. so should udev be required?

**Comment by simonvanderveldt** [comment]
> ok. so should udev be required?

No, it doesn't have to be, sysfs alone can be enough.
I think I know how to fix this issue, will give it a try this weekend.

**Comment by simonvanderveldt** [comment]
Whilst for some reason I'm currently no longer able to reproduce this issue we should fix the `asprintf` warning because it opens the door for vulnerabilities. For some more info see here https://web.archive.org/web/20090505140305/http://blogs.23.nu:80/ilja/2006/10/antville-12995/

@wrl I think this would be the patch, does this look right?
I'm not sure if `buf` being `NULL` could cause any issues elsewhere in the code?
```
        path = strchr(path, '/') + 1;
 
-       asprintf(&buf, FTDI_PATH "/*/%s", path);
+  if (asprintf(&buf, FTDI_PATH "/*/%s", path) < 0) {
+         buf = NULL;
+  }
        glob(buf, 0, NULL, &gb);
        free(buf);
```
