### ISSUE TITLE
Add option to not run ldconfig (or don't run it at all?)

### ISSUE THREAD

**Issue by simonvanderveldt** [monome/libmonome#52]
Currently `wscript` always calls `ldconfig` after building. See https://github.com/monome/libmonome/blob/3be6a37c8e30a7cf6eae6c202b2951d21abc7c76/wscript#L237

Gentoo uses a sandbox that doesn't allow writing to the root filesystem when building package. Since `ldconfig` tries to write to `/etc/ld.so.cache` this causes a sandbox violation and building/installing the package fails.

I wanted to discuss how to address this.
I don't know why the `ldconfig` option was added (there's no mention of the reason in the commit), but normally the package manager does these kinds of things. If it's not necessary maybe it can be removed?
If it is for some reason then it could become an option? Or it could become and option to disable it.

What would be the preferred way to address this?

**Comment by wrl** [comment]
fine with just removing it.
