### ISSUE TITLE
OpenBSD support

### ISSUE THREAD

**Issue by jesselucas** [monome/libmonome#74]
I'm attempting to build libmonome for OpenBSD 7.0 and running into issues. Is building for OpenBSD still supported?

I was able to hack together a build but not successfully run the examples by removing the ldl check, using the posix.c and darwin.c platform files and removing the OFILL flag: https://github.com/jesselucas/libmonome

I'm guessing the darwin.c platform file is the issue with OpenBSD but before trying more wanted to make sure there wasn't an easier path to build that I was missing.

**Comment by tehn** [comment]
i apologize: the readme was written so long ago by the original maintainer, and i've not been aware of many attempts to run libmonome on OpenBSD--- so i'd gladly accept any fixes, otherwise i'll need to simply remove OpenBSD from the list of supported systems

**Comment by jesselucas** [comment]
Thanks for the reply! I will try to update `monome_platform_get_dev_serial` this week.
